import { axiosInstance } from "../axios";

export type RegistrationTokenRole = "school owner" | "teacher" | "head teacher";
export type TokenStatus = "pending" | "used" | "expired";

export interface GenerateTokenDto {
  role: RegistrationTokenRole;
  expiresInDays?: number;
}

export interface ValidateTokenDto {
  token: string;
}

export interface RegisterWithTokenDto {
  token: string;
  email: string;
  password: string;
  name?: string;
  phone?: string;
  yearsOfExperience?: number;
  qualifications?: string[];
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  emergencyContact?: string;
  additionalNotes?: string;
  // School Owner specific fields
  schoolName?: string;
  schoolCity?: string;
  schoolDistrict?: string;
  schoolPhoneNumber?: string;
  schoolEmail?: string;
  schoolWebsite?: string;
  schoolType?: string;
  establishedYear?: number;
  studentCapacity?: number;
  schoolDescription?: string;
  schoolAddress?: string;
}

export interface GeneratedTokenResponse {
  token: string;
  role: RegistrationTokenRole;
  schoolId: string | null;
  expiresAt: string;
  status: TokenStatus;
  createdAt: string;
}

export interface ValidateTokenResponse {
  valid: boolean;
  role: RegistrationTokenRole;
  schoolId: string | null;
  expiresAt: string;
}

export interface RegisterResponse {
  message: string;
  user: {
    id: string;
    email: string;
    name?: string;
    role: string;
    school?: {
      id: string;
      name: string;
    };
  };
}

export interface RegistrationToken {
  _id: string;
  token: string;
  role: RegistrationTokenRole;
  schoolId: {
    _id: string;
    name: string;
  } | null;
  expiresAt: string;
  createdBy: {
    _id: string;
    email: string;
    name: string;
  };
  status: TokenStatus;
  usedAt: string | null;
  usedBy: {
    _id: string;
    email: string;
    name: string;
  } | null;
  usedFromIp: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface TokenStatsResponse {
  total: number;
  pending: number;
  used: number;
  expired: number;
}

const basePath = "/api/registration-tokens";

export const registrationTokensApi = {
  /**
   * Generate a registration token
   */
  generateToken: async (
    data: GenerateTokenDto
  ): Promise<GeneratedTokenResponse> => {
    const { data: response } = await axiosInstance.post<GeneratedTokenResponse>(
      `${basePath}/generate`,
      data
    );
    return response;
  },

  /**
   * Validate a registration token
   */
  validateToken: async (
    data: ValidateTokenDto
  ): Promise<ValidateTokenResponse> => {
    const { data: response } = await axiosInstance.post<ValidateTokenResponse>(
      `${basePath}/validate`,
      data
    );
    return response;
  },

  /**
   * Register a new user with a token
   */
  registerWithToken: async (
    data: RegisterWithTokenDto
  ): Promise<RegisterResponse> => {
    const { data: response } = await axiosInstance.post<RegisterResponse>(
      "/api/auth/register",
      data
    );
    return response;
  },

  /**
   * Get all tokens generated by the authenticated user
   */
  getMyTokens: async (params?: {
    role?: RegistrationTokenRole;
  }): Promise<RegistrationToken[]> => {
    const { data } = await axiosInstance.get<RegistrationToken[]>(
      `${basePath}/my-tokens`,
      { params }
    );
    return data;
  },

  /**
   * Get token statistics for the authenticated user
   */
  getTokenStats: async (): Promise<TokenStatsResponse> => {
    const { data } = await axiosInstance.get<TokenStatsResponse>(
      `${basePath}/my-tokens/stats`
    );
    return data;
  },
};

