"use client";

import React from "react";
import { StaffDataTable } from "./staff-data-table";
import { StaffStats } from "./staff-stats";
import { AddStaffDialog } from "./add-staff-dialog";

// Sample staff data
const staffData = [
  {
    id: 1,
    name: "Robert Martinez",
    email: "robert.martinez@school.edu",
    position: "Principal",
    department: "Administration",
    status: "Active",
    employmentType: "Full-time",
    salary: "$85,000",
    hireDate: "2018-08-15",
    phone: "+1 (555) 111-2222",
    shift: "Day",
  },
  {
    id: 2,
    name: "Jennifer Adams",
    email: "jennifer.adams@school.edu",
    position: "Vice Principal",
    department: "Administration",
    status: "Active",
    employmentType: "Full-time",
    salary: "$72,000",
    hireDate: "2019-09-01",
    phone: "+1 (555) 222-3333",
    shift: "Day",
  },
  {
    id: 3,
    name: "Thomas Brown",
    email: "thomas.brown@school.edu",
    position: "IT Administrator",
    department: "IT Support",
    status: "Active",
    employmentType: "Full-time",
    salary: "$58,000",
    hireDate: "2020-01-10",
    phone: "+1 (555) 333-4444",
    shift: "Day",
  },
  {
    id: 4,
    name: "Patricia Wilson",
    email: "patricia.wilson@school.edu",
    position: "School Nurse",
    department: "Health Services",
    status: "Active",
    employmentType: "Full-time",
    salary: "$52,000",
    hireDate: "2019-03-20",
    phone: "+1 (555) 444-5555",
    shift: "Day",
  },
  {
    id: 5,
    name: "Daniel Lee",
    email: "daniel.lee@school.edu",
    position: "Librarian",
    department: "Library",
    status: "Active",
    employmentType: "Full-time",
    salary: "$45,000",
    hireDate: "2020-08-05",
    phone: "+1 (555) 555-6666",
    shift: "Day",
  },
  {
    id: 6,
    name: "Michelle Taylor",
    email: "michelle.taylor@school.edu",
    position: "Counselor",
    department: "Student Services",
    status: "Active",
    employmentType: "Full-time",
    salary: "$54,000",
    hireDate: "2018-11-12",
    phone: "+1 (555) 666-7777",
    shift: "Day",
  },
  {
    id: 7,
    name: "Kevin Anderson",
    email: "kevin.anderson@school.edu",
    position: "Security Guard",
    department: "Security",
    status: "Active",
    employmentType: "Full-time",
    salary: "$38,000",
    hireDate: "2021-02-01",
    phone: "+1 (555) 777-8888",
    shift: "Night",
  },
  {
    id: 8,
    name: "Sandra Moore",
    email: "sandra.moore@school.edu",
    position: "Receptionist",
    department: "Administration",
    status: "Active",
    employmentType: "Full-time",
    salary: "$35,000",
    hireDate: "2020-06-15",
    phone: "+1 (555) 888-9999",
    shift: "Day",
  },
  {
    id: 9,
    name: "Richard Clark",
    email: "richard.clark@school.edu",
    position: "Janitor",
    department: "Maintenance",
    status: "Active",
    employmentType: "Part-time",
    salary: "$28,000",
    hireDate: "2021-09-10",
    phone: "+1 (555) 999-0000",
    shift: "Evening",
  },
  {
    id: 10,
    name: "Nancy White",
    email: "nancy.white@school.edu",
    position: "Cafeteria Manager",
    department: "Food Services",
    status: "Active",
    employmentType: "Full-time",
    salary: "$42,000",
    hireDate: "2019-05-20",
    phone: "+1 (555) 000-1111",
    shift: "Day",
  },
  {
    id: 11,
    name: "George Harris",
    email: "george.harris@school.edu",
    position: "Bus Driver",
    department: "Transportation",
    status: "Active",
    employmentType: "Part-time",
    salary: "$32,000",
    hireDate: "2020-10-01",
    phone: "+1 (555) 111-2223",
    shift: "Morning/Afternoon",
  },
  {
    id: 12,
    name: "Barbara Lewis",
    email: "barbara.lewis@school.edu",
    position: "HR Manager",
    department: "Human Resources",
    status: "Active",
    employmentType: "Full-time",
    salary: "$65,000",
    hireDate: "2018-07-15",
    phone: "+1 (555) 222-3334",
    shift: "Day",
  },
  {
    id: 13,
    name: "Christopher Walker",
    email: "christopher.walker@school.edu",
    position: "Accountant",
    department: "Finance",
    status: "Active",
    employmentType: "Full-time",
    salary: "$60,000",
    hireDate: "2019-12-01",
    phone: "+1 (555) 333-4445",
    shift: "Day",
  },
  {
    id: 14,
    name: "Elizabeth Hall",
    email: "elizabeth.hall@school.edu",
    position: "Lab Technician",
    department: "Science Lab",
    status: "On Leave",
    employmentType: "Full-time",
    salary: "$48,000",
    hireDate: "2020-04-10",
    phone: "+1 (555) 444-5556",
    shift: "Day",
  },
  {
    id: 15,
    name: "Steven Young",
    email: "steven.young@school.edu",
    position: "Groundskeeper",
    department: "Maintenance",
    status: "Active",
    employmentType: "Full-time",
    salary: "$36,000",
    hireDate: "2021-03-15",
    phone: "+1 (555) 555-6667",
    shift: "Day",
  },
];

export default function AdminStaffPage() {
  return (
    <div className="py-4">
      <div className="flex items-center justify-between px-4">
        <h2 className="text-3xl font-semibold text-primary">Manage Staff</h2>
        <AddStaffDialog />
      </div>
      <StaffStats />
      <StaffDataTable data={staffData} />
    </div>
  );
}
