import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-toastify";
import {
  registrationTokensApi,
  type GenerateTokenDto,
  type ValidateTokenDto,
  type RegisterWithTokenDto,
  type RegistrationTokenRole,
} from "@/lib/api/registration-tokens";

// Query keys
export const registrationTokenKeys = {
  all: ["registration-tokens"] as const,
  myTokens: (role?: RegistrationTokenRole) =>
    ["registration-tokens", "my-tokens", role] as const,
  stats: () => ["registration-tokens", "stats"] as const,
};

/**
 * Hook to generate a registration token
 */
export function useGenerateToken() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: GenerateTokenDto) =>
      registrationTokensApi.generateToken(data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({
        queryKey: registrationTokenKeys.myTokens(),
      });
      queryClient.invalidateQueries({
        queryKey: registrationTokenKeys.stats(),
      });
      toast.success(
        `Token generated successfully! Token: ${response.token.substring(0, 20)}...`
      );
    },
    onError: (error: any) => {
      const message =
        error?.response?.data?.message || "Failed to generate token";
      toast.error(message);
    },
  });
}

/**
 * Hook to validate a registration token
 */
export function useValidateToken() {
  return useMutation({
    mutationFn: (data: ValidateTokenDto) =>
      registrationTokensApi.validateToken(data),
    onError: (error: any) => {
      const message =
        error?.response?.data?.message || "Invalid registration token";
      toast.error(message);
    },
  });
}

/**
 * Hook to register a new user with a token
 */
export function useRegisterWithToken() {
  return useMutation({
    mutationFn: (data: RegisterWithTokenDto) =>
      registrationTokensApi.registerWithToken(data),
    onSuccess: () => {
      toast.success("Registration successful! You can now log in.");
    },
    onError: (error: any) => {
      const message =
        error?.response?.data?.message || "Registration failed";
      toast.error(message);
    },
  });
}

/**
 * Hook to get all tokens generated by the authenticated user
 */
export function useMyTokens(role?: RegistrationTokenRole) {
  return useQuery({
    queryKey: registrationTokenKeys.myTokens(role),
    queryFn: () => registrationTokensApi.getMyTokens({ role }),
  });
}

/**
 * Hook to get token statistics
 */
export function useTokenStats() {
  return useQuery({
    queryKey: registrationTokenKeys.stats(),
    queryFn: () => registrationTokensApi.getTokenStats(),
  });
}

